[build]
builder = "NIXPACKS"
buildCommand = "npm --prefix backend ci && npm --prefix backend run build"

[deploy]
startCommand = "npm --prefix backend run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
